services:
  - type: web
    name: minerbytsfree-server
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: minerbytsfree-server
      - key: PROJECT_NAME
        value: minerbytsfree
      - key: ADMIN_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
